services:
  # MariaDB 데이터베이스
  mariadb:
    image: mariadb:11.4
    container_name: spring-mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: log2doc
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - ./data/mariadb:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - spring-network

  # Redis 캐시 서버
  redis:
    image: redis:latest
    container_name: spring-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    command: redis-server --appendonly yes --requirepass 1234
    networks:
      - spring-network

# 볼륨 설정
volumes:
  mariadb_data:
    driver: local
  redis_data:
    driver: local

# 네트워크 설정
networks:
  spring-network:
    driver: bridge